services:
  postgres:
    image: postgres:16
    container_name: postgres_container_Task
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task_dev
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
